name: Preprocessing Workflow

on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nbconvert jupyter pandas numpy scikit-learn

      - name: Execute preprocessing notebook
        run: |
          jupyter nbconvert --to notebook --execute preprocessing.ipynb --output preprocessing_output.ipynb

      - name: List output files
        run: ls -lh
